import { NextResponse } from 'next/server';

export const dynamic = 'force-dynamic';

export interface MoEngageFlow {
  id: string;
    name: string;
      status: 'Active' | 'Paused' | 'Draft' | 'Completed' | 'Stopped';
        trigger: string;
          channel: string;
            enrolledUsers: number;
              completedUsers: number;
                exitedUsers: number;
                  conversionRate: number;
                    createdAt: string;
                      updatedAt: string;
                        tags: string[];
                        }

                        function getMockFlows(): MoEngageFlow[] {
                          const today = new Date();
                            const daysAgo = (n: number) => {
                                const d = new Date(today);
                                    d.setDate(d.getDate() - n);
                                        return d.toISOString();
                                          };

                                            return [
                                                {
                                                      id: 'flow_001',
                                                            name: 'Welcome Series — New User Onboarding',
                                                                  status: 'Active',
                                                                        trigger: 'User Signup',
                                                                              channel: 'Email + Push',
                                                                                    enrolledUsers: 12450,
                                                                                          completedUsers: 9800,
                                                                                                exitedUsers: 1230,
                                                                                                      conversionRate: 78.7,
                                                                                                            createdAt: daysAgo(45),
                                                                                                                  updatedAt: daysAgo(2),
                                                                                                                        tags: ['onboarding', 'email', 'push'],
                                                                                                                            },
                                                                                                                                {
                                                                                                                                      id: 'flow_002',
                                                                                                                                            name: 'Cart Abandonment Recovery',
                                                                                                                                                  status: 'Active',
                                                                                                                                                        trigger: 'Cart Abandoned',
                                                                                                                                                              channel: 'Email + WhatsApp',
                                                                                                                                                                    enrolledUsers: 8320,
                                                                                                                                                                          completedUsers: 5100,
                                                                                                                                                                                exitedUsers: 920,
                                                                                                                                                                                      conversionRate: 61.3,
                                                                                                                                                                                            createdAt: daysAgo(30),
                                                                                                                                                                                                  updatedAt: daysAgo(1),
                                                                                                                                                                                                        tags: ['retention', 'email', 'whatsapp'],
                                                                                                                                                                                                            },
                                                                                                                                                                                                                {
                                                                                                                                                                                                                      id: 'flow_003',
                                                                                                                                                                                                                            name: 'Win-Back Inactive Users (60d)',
                                                                                                                                                                                                                                  status: 'Active',
                                                                                                                                                                                                                                        trigger: 'Inactivity — 60 days',
                                                                                                                                                                                                                                              channel: 'Push + SMS',
                                                                                                                                                                                                                                                    enrolledUsers: 5670,
                                                                                                                                                                                                                                                          completedUsers: 2100,
                                                                                                                                                                                                                                                                exitedUsers: 3100,
                                                                                                                                                                                                                                                                      conversionRate: 37.0,
                                                                                                                                                                                                                                                                            createdAt: daysAgo(60),
                                                                                                                                                                                                                                                                                  updatedAt: daysAgo(5),
                                                                                                                                                                                                                                                                                        tags: ['win-back', 'push', 'sms'],
                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                      id: 'flow_004',
                                                                                                                                                                                                                                                                                                            name: 'Post-Purchase Cross-Sell',
                                                                                                                                                                                                                                                                                                                  status: 'Active',
                                                                                                                                                                                                                                                                                                                        trigger: 'Order Completed',
                                                                                                                                                                                                                                                                                                                              channel: 'Email + In-App',
                                                                                                                                                                                                                                                                                                                                    enrolledUsers: 19800,
                                                                                                                                                                                                                                                                                                                                          completedUsers: 15600,
                                                                                                                                                                                                                                                                                                                                                exitedUsers: 980,
                                                                                                                                                                                                                                                                                                                                                      conversionRate: 78.8,
                                                                                                                                                                                                                                                                                                                                                            createdAt: daysAgo(20),
                                                                                                                                                                                                                                                                                                                                                                  updatedAt: daysAgo(0),
                                                                                                                                                                                                                                                                                                                                                                        tags: ['cross-sell', 'email', 'in-app'],
                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                      id: 'flow_005',
                                                                                                                                                                                                                                                                                                                                                                                            name: 'Loyalty Tier Upgrade Nudge',
                                                                                                                                                                                                                                                                                                                                                                                                  status: 'Active',
                                                                                                                                                                                                                                                                                                                                                                                                        trigger: 'Near Loyalty Threshold',
                                                                                                                                                                                                                                                                                                                                                                                                              channel: 'Push + Email',
                                                                                                                                                                                                                                                                                                                                                                                                                    enrolledUsers: 3240,
                                                                                                                                                                                                                                                                                                                                                                                                                          completedUsers: 2180,
                                                                                                                                                                                                                                                                                                                                                                                                                                exitedUsers: 310,
                                                                                                                                                                                                                                                                                                                                                                                                                                      conversionRate: 67.3,
                                                                                                                                                                                                                                                                                                                                                                                                                                            createdAt: daysAgo(14),
                                                                                                                                                                                                                                                                                                                                                                                                                                                  updatedAt: daysAgo(1),
                                                                                                                                                                                                                                                                                                                                                                                                                                                        tags: ['loyalty', 'push', 'email'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      id: 'flow_006',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            name: 'Trial Expiry Conversion',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  status: 'Active',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        trigger: 'Trial Ending in 3 Days',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              channel: 'Email + WhatsApp + Push',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    enrolledUsers: 2890,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          completedUsers: 1340,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                exitedUsers: 890,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      conversionRate: 46.4,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            createdAt: daysAgo(25),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  updatedAt: daysAgo(3),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        tags: ['conversion', 'email', 'whatsapp'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      id: 'flow_007',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            name: 'Referral Program Activation',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  status: 'Paused',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        trigger: 'First Purchase',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              channel: 'Email + SMS',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    enrolledUsers: 6710,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          completedUsers: 3200,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                exitedUsers: 1400,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      conversionRate: 47.7,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            createdAt: daysAgo(40),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  updatedAt: daysAgo(8),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        tags: ['referral', 'email', 'sms'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      id: 'flow_008',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            name: 'Event Reminder — Webinar',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  status: 'Draft',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        trigger: 'Event Registration',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              channel: 'Email + Push',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    enrolledUsers: 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          completedUsers: 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                exitedUsers: 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      conversionRate: 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            createdAt: daysAgo(2),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  updatedAt: daysAgo(0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        tags: ['event', 'email', 'push'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      id: 'flow_009',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            name: 'Birthday / Anniversary Celebration',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  status: 'Active',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        trigger: 'User Birthday',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              channel: 'Email + WhatsApp',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    enrolledUsers: 4500,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          completedUsers: 4200,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                exitedUsers: 120,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      conversionRate: 93.3,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            createdAt: daysAgo(90),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  updatedAt: daysAgo(0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        tags: ['lifecycle', 'email', 'whatsapp'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      id: 'flow_010',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            name: 'Payment Failure Recovery',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  status: 'Active',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        trigger: 'Payment Failed',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              channel: 'Email + Push + WhatsApp',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    enrolledUsers: 1230,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          completedUsers: 880,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                exitedUsers: 230,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      conversionRate: 71.5,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            createdAt: daysAgo(35),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  updatedAt: daysAgo(1),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        tags: ['payment', 'email', 'push'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              export async function GET() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const flows = getMockFlows();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const activeFlows = flows.filter(f => f.status === 'Active');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const totalEnrolled = flows.reduce((sum, f) => sum + f.enrolledUsers, 0);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const avgConversionRate =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      activeFlows.length > 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ? activeFlows.reduce((sum, f) => sum + f.conversionRate, 0) / activeFlows.length
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      : 0;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return NextResponse.json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                flows,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      summary: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              total: flows.length,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      active: activeFlows.length,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              paused: flows.filter(f => f.status === 'Paused').length,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      draft: flows.filter(f => f.status === 'Draft').length,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              totalEnrolled,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      avgConversionRate: parseFloat(avgConversionRate.toFixed(1)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  } catch (error)